In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

data = pd.read_csv('student-por.csv')

In [10]:
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

In [11]:
data.drop(['school','sex','address'],axis =1,inplace = True)

In [12]:
data.head()

,age,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,18,GT3,A,4,4,at_home,teacher,course,mother,2,...,4,3,4,1,1,3,4,0,11,11
1,17,GT3,T,1,1,at_home,other,course,father,1,...,5,3,3,1,1,3,2,9,11,11
2,15,LE3,T,1,1,at_home,other,other,mother,1,...,4,3,2,2,3,3,6,12,13,12
3,15,GT3,T,4,2,health,services,home,mother,1,...,3,2,2,1,1,5,0,14,14,14
4,16,GT3,T,3,3,other,other,home,father,1,...,4,3,2,1,2,5,0,11,13,13

In [17]:
data.iloc[:,9:]

,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,2,2,0,yes,no,no,no,yes,yes,no,...,4,3,4,1,1,3,4,0,11,11
1,1,2,0,no,yes,no,no,no,yes,yes,...,5,3,3,1,1,3,2,9,11,11
2,1,2,0,yes,no,no,no,yes,yes,yes,...,4,3,2,2,3,3,6,12,13,12
3,1,3,0,no,yes,no,yes,yes,yes,yes,...,3,2,2,1,1,5,0,14,14,14
4,1,2,0,no,yes,no,no,yes,yes,no,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,1,3,1,no,no,no,yes,no,yes,yes,...,5,4,2,1,2,5,4,10,11,10
645,1,2,0,no,yes,no,no,yes,yes,yes,...,4,3,4,1,1,1,4,15,15,16
646,2,2,0,no,no,no,yes,yes,yes,no,...,1,1,1,1,1,5,6,11,12,9
647,2,1,0,no,no,no,no,no,yes,yes,...,2,4,5,3,4,2,6,10,10,10
648,3,1,0,no,no,no,no,no,yes,yes,...,4,4,1,3,4,5,4,10,11,11

In [16]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [25]:
val = data.columns[12:20]
for col in val:
    data[col] = LabelEncoder().fit_transform(data[col])

In [29]:
data[val].head()

   schoolsup  famsup  paid  activities  nursery  higher  internet  romantic
0          1       0     0           0        1       1         0         0
1          0       1     0           0        0       1         1         0
2          1       0     0           0        1       1         1         0
3          0       1     0           1        1       1         1         1
4          0       1     0           0        1       1         0         0

In [28]:
data.head()

,age,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,18,GT3,A,4,4,at_home,teacher,course,mother,2,...,4,3,4,1,1,3,4,0,11,11
1,17,GT3,T,1,1,at_home,other,course,father,1,...,5,3,3,1,1,3,2,9,11,11
2,15,LE3,T,1,1,at_home,other,other,mother,1,...,4,3,2,2,3,3,6,12,13,12
3,15,GT3,T,4,2,health,services,home,mother,1,...,3,2,2,1,1,5,0,14,14,14
4,16,GT3,T,3,3,other,other,home,father,1,...,4,3,2,1,2,5,0,11,13,13

In [33]:
data['guardian'].unique()

array(['mother', 'father', 'other'], dtype=object)

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         649 non-null    int64
 1   famsize     649 non-null    object
 2   Pstatus     649 non-null    object
 3   Medu        649 non-null    int64
 4   Fedu        649 non-null    int64
 5   Mjob        649 non-null    object
 6   Fjob        649 non-null    object
 7   reason      649 non-null    object
 8   guardian    649 non-null    object
 9   traveltime  649 non-null    int64
 10  studytime   649 non-null    int64
 11  failures    649 non-null    int64
 12  schoolsup   649 non-null    int32
 13  famsup      649 non-null    int32
 14  paid        649 non-null    int32
 15  activities  649 non-null    int32
 16  nursery     649 non-null    int32
 17  higher      649 non-null    int32
 18  internet    649 non-null    int32
 19  romantic    649 non-null    int32
 20  famrel      649 non-null    int64
 21  freetime    649 non-null    int64
 22  goout       649 non-null    int64
 23  Dalc        649 non-null    int64
 24  Walc        649 non-null    int64
 25  health      649 non-null    int64
 26  absences    649 non-null    int64
 27  G1          649 non-null    int64
 28  G2          649 non-null    int64
 29  G3          649 non-null    int64
dtypes: int32(8), int64(16), object(6)
memory usage: 132.0+ KB

In [35]:
val = ['famsize','Pstatus']
for col in val:
    data[col] = LabelEncoder().fit_transform(data[col])

In [37]:
data.drop(['Mjob','Fjob','reason','guardian'],axis = 1,inplace = True)

In [38]:
data.head()

,age,famsize,Pstatus,Medu,Fedu,traveltime,studytime,failures,schoolsup,famsup,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,18,0,0,4,4,2,2,0,1,0,...,4,3,4,1,1,3,4,0,11,11
1,17,0,1,1,1,1,2,0,0,1,...,5,3,3,1,1,3,2,9,11,11
2,15,1,1,1,1,1,2,0,1,0,...,4,3,2,2,3,3,6,12,13,12
3,15,0,1,4,2,1,3,0,0,1,...,3,2,2,1,1,5,0,14,14,14
4,16,0,1,3,3,1,2,0,0,1,...,4,3,2,1,2,5,0,11,13,13

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         649 non-null    int64
 1   famsize     649 non-null    int32
 2   Pstatus     649 non-null    int32
 3   Medu        649 non-null    int64
 4   Fedu        649 non-null    int64
 5   traveltime  649 non-null    int64
 6   studytime   649 non-null    int64
 7   failures    649 non-null    int64
 8   schoolsup   649 non-null    int32
 9   famsup      649 non-null    int32
 10  paid        649 non-null    int32
 11  activities  649 non-null    int32
 12  nursery     649 non-null    int32
 13  higher      649 non-null    int32
 14  internet    649 non-null    int32
 15  romantic    649 non-null    int32
 16  famrel      649 non-null    int64
 17  freetime    649 non-null    int64
 18  goout       649 non-null    int64
 19  Dalc        649 non-null    int64
 20  Walc        649 non-null    int64
 21  health      649 non-null    int64
 22  absences    649 non-null    int64
 23  G1          649 non-null    int64
 24  G2          649 non-null    int64
 25  G3          649 non-null    int64
dtypes: int32(10), int64(16)
memory usage: 106.6 KB

In [41]:
X = data.drop(['G3'],axis =1)
Y = data['G3']

In [42]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42)

In [43]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [44]:
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [45]:
y_pred = model.predict(X_test)

In [51]:
mse = mean_squared_error(Y_test,y_pred)
mse

1.3944062783033355

In [52]:
r2 = r2_score(Y_test,y_pred)
r2

0.8570091375007501

In [53]:
data.corr()

,age,famsize,Pstatus,Medu,Fedu,traveltime,studytime,failures,schoolsup,famsup,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
age,1.000000,-0.002470,-0.005631,-0.107832,-0.121050,0.034490,-0.008415,0.319968,-0.167841,-0.101894,...,-0.020559,-0.004910,0.112805,0.134768,0.086357,-0.008750,0.149998,-0.174322,-0.107119,-0.106505
famsize,-0.002470,1.000000,-0.239608,-0.014325,-0.039538,0.012794,-0.010945,-0.066068,-0.056405,-0.039819,...,0.004641,-0.021257,-0.004312,0.060482,0.081958,0.002448,0.004645,0.047230,0.038891,0.045016
Pstatus,-0.005631,-0.239608,1.000000,-0.057174,-0.031856,0.040633,-0.008748,-0.009881,-0.009456,0.010203,...,0.051303,0.037585,0.031086,0.041513,0.070976,0.012638,-0.117492,0.015251,0.018689,-0.000754
Medu,-0.107832,-0.014325,-0.057174,1.000000,0.647477,-0.265079,0.097006,-0.172210,-0.022168,0.120491,...,0.024421,-0.019686,0.009536,-0.007018,-0.019766,0.004614,-0.008577,0.260472,0.264035,0.240151
Fedu,-0.121050,-0.039538,-0.031856,0.647477,1.000000,-0.208288,0.050400,-0.165915,0.023572,0.135191,...,0.020256,0.006841,0.027690,0.000061,0.038445,0.044910,0.029859,0.217501,0.225139,0.211800
traveltime,0.034490,0.012794,0.040633,-0.265079,-0.208288,1.000000,-0.063154,0.097730,-0.044807,-0.039289,...,-0.009521,0.000937,0.057454,0.092824,0.057007,-0.048261,-0.008149,-0.154120,-0.154489,-0.127173
studytime,-0.008415,-0.010945,-0.008748,0.097006,0.050400,-0.063154,1.000000,-0.147441,0.089316,0.143509,...,-0.004127,-0.068829,-0.075442,-0.137585,-0.214925,-0.056433,-0.118389,0.260875,0.240498,0.249789
failures,0.319968,-0.066068,-0.009881,-0.172210,-0.165915,0.097730,-0.147441,1.000000,-0.000745,-0.006982,...,-0.062645,0.108995,0.045078,0.105949,0.082266,0.035588,0.122779,-0.384210,-0.385782,-0.393316
schoolsup,-0.167841,-0.056405,-0.009456,-0.022168,0.023572,-0.044807,0.089316,-0.000745,1.000000,0.075402,...,-0.012038,-0.015611,-0.058124,-0.028076,-0.098275,0.022760,-0.059503,-0.071779,-0.056624,-0.066405
famsup,-0.101894,-0.039819,0.010203,0.120491,0.135191,-0.039289,0.143509,-0.006982,0.075402,1.000000,...,0.015228,0.003764,0.017262,-0.016844,-0.065605,0.018803,0.041980,0.038255,0.038141,0.059206
paid,-0.005458,-0.050253,0.015923,0.113973,0.094628,-0.044842,-0.002314,0.069416,0.040512,0.094297,...,0.031937,-0.049574,-0.006683,0.051986,0.035682,0.063203,-0.035959,-0.062784,-0.033925,-0.054898
activities,-0.054279,-0.014790,0.101555,0.119354,0.079700,-0.033376,0.070080,0.000561,-0.030246,-0.007433,...,0.057597,0.150329,0.088582,0.022592,0.032824,0.013001,-0.015115,0.080123,0.067154,0.059791
nursery,-0.021441,0.100686,-0.032724,0.125951,0.074863,-0.011509,0.042630,-0.069241,0.017846,0.027799,...,0.041055,-0.007096,0.018679,-0.078376,-0.075748,0.001701,-0.040574,0.031172,0.039867,0.028752
higher,-0.265497,0.004523,0.022726,0.213896,0.191735,-0.071958,0.188256,-0.309400,0.085355,0.085340,...,0.048239,-0.102618,-0.069105,-0.131663,-0.084327,0.017290,-0.129891,0.349030,0.331953,0.332172
internet,0.013115,0.013357,0.059754,0.266052,0.183483,-0.190826,0.037529,-0.095330,-0.025942,0.071891,...,0.082214,0.063268,0.092869,0.042811,0.060651,-0.022792,0.067301,0.139931,0.147909,0.150025
romantic,0.178810,-0.032936,-0.053828,-0.030992,-0.067675,0.004751,0.033036,0.069901,-0.094310,-0.023398,...,-0.044920,0.027112,-0.000520,0.062042,-0.019971,-0.018025,0.079489,-0.074973,-0.097937,-0.090583
famrel,-0.020559,0.004641,0.051303,0.024421,0.020256,-0.009521,-0.004127,-0.062645,-0.012038,0.015228,...,1.000000,0.129216,0.089707,-0.075767,-0.093511,0.109559,-0.089534,0.048795,0.089588,0.063361
freetime,-0.004910,-0.021257,0.037585,-0.019686,0.006841,0.000937,-0.068829,0.108995,-0.015611,0.003764,...,0.129216,1.000000,0.346352,0.109904,0.120244,0.084526,-0.018716,-0.094497,-0.106678,-0.122705
goout,0.112805,-0.004312,0.031086,0.009536,0.027690,0.057454,-0.075442,0.045078,-0.058124,0.017262,...,0.089707,0.346352,1.000000,0.245126,0.388680,-0.015741,0.085374,-0.074053,-0.079469,-0.087641
Dalc,0.134768,0.060482,0.041513,-0.007018,0.000061,0.092824,-0.137585,0.105949,-0.028076,-0.016844,...,-0.075767,0.109904,0.245126,1.000000,0.616561,0.059067,0.172952,-0.195171,-0.189480,-0.204719
Walc,0.086357,0.081958,0.070976,-0.019766,0.038445,0.057007,-0.214925,0.082266,-0.098275,-0.065605,...,-0.093511,0.120244,0.388680,0.616561,1.000000,0.114988,0.156373,-0.155649,-0.164852,-0.176619
health,-0.008750,0.002448,0.012638,0.004614,0.044910,-0.048261,-0.056433,0.035588,0.022760,0.018803,...,0.109559,0.084526,-0.015741,0.059067,0.114988,1.000000,-0.030235,-0.051647,-0.082179,-0.098851
absences,0.149998,0.004645,-0.117492,-0.008577,0.029859,-0.008149,-0.118389,0.122779,-0.059503,0.041980,...,-0.089534,-0.018716,0.085374,0.172952,0.156373,-0.030235,1.000000,-0.147149,-0.124745,-0.091379
G1,-0.174322,0.047230,0.015251,0.260472,0.217501,-0.154120,0.260875,-0.384210,-0.071779,0.038255,...,0.048795,-0.094497,-0.074053,-0.195171,-0.155649,-0.051647,-0.147149,1.000000,0.864982,0.826387
G2,-0.107119,0.038891,0.018689,0.264035,0.225139,-0.154489,0.240498,-0.385782,-0.056624,0.038141,...,0.089588,-0.106678,-0.079469,-0.189480,-0.164852,-0.082179,-0.124745,0.864982,1.000000,0.918548
G3,-0.106505,0.045016,-0.000754,0.240151,0.211800,-0.127173,0.249789,-0.393316,-0.066405,0.059206,...,0.063361,-0.122705,-0.087641,-0.204719,-0.176619,-0.098851,-0.091379,0.826387,0.918548,1.000000

In [56]:
df.count()

Predict    130
dtype: int64

In [59]:
Y_test.count()

130